### ISSUE TITLE
full screen glitch

### ISSUE THREAD

**Issue by DaDUDEA** [Jonitr0/WarnoModEditor#1]
![image](https://github.com/Jonitr0/WarnoModEditor/assets/139646214/b71855d1-8715-45fb-a2d2-ba5dea7dd0a6)
does this, i dont know why

**Comment by DaDUDEA** [comment]
look at the corners

**Comment by Jonitr0** [comment]
Hi, Thanks for the report. Looks like there is something wrong with the shadow effect that is displayed when used windowed. What kind of screen setup do you have? Multiple screens or just one? Does this always happen in fullscreen mode?

**Comment by DaDUDEA** [comment]
> Hi, Thanks for the report. Looks like there is something wrong with the shadow effect that is displayed when used windowed. What kind of screen setup do you have? Multiple screens or just one? Does this always happen in fullscreen mode?

yes, it happens when im in full screen, and i only have 1 monitor.

**Comment by chen984** [comment]
> Hi, Thanks for the report. Looks like there is something wrong with the shadow effect that is displayed when used windowed. What kind of screen setup do you have? Multiple screens or just one? Does this always happen in fullscreen mode?

It happens when i open more than 14(depend on the lenght of the filename,usually between 14 and 16) label pages,close some label pages than restart the program can fix it.

**Comment by Jonitr0** [comment]
fixed with 0.4.0, tab widget will now display scroll buttons when more tabs are present than it is currently wide
