### ISSUE TITLE
Can't find "Hemtt" in the unitedescriptior.ndf file

### ISSUE THREAD

**Issue by bofhlusr** [Jonitr0/WarnoModEditor#2]
The unit is a supply unit for the US 3rd Armored Division.

![image](https://github.com/Jonitr0/WarnoModEditor/assets/87720208/d2e7a6b3-06b1-4d50-8540-c8f3df283b41)

**Comment by Jonitr0** [comment]
The search is not case-sensitive for now. You'll actually have to enter "HEMTT" to find it. I'll consider a case-insensitive search for a future version

**Comment by bofhlusr** [comment]
Thank you for the quick reply. Nice work. I've been using Notepad++ and Kedit (which has selective line editing capabilities such as being able to fold or collapse lines in the file).  Love the WME default color theme.  I'll start using the WME editor to check it out.
