### ISSUE TITLE
Did Moncey update affect the editor?

### ISSUE THREAD

**Issue by bofhlusr** [Jonitr0/WarnoModEditor#4]
I used to be able to but now I can't change the Starting Point.

**Comment by Jonitr0** [comment]
I'll look into this

**Comment by bofhlusr** [comment]
Hi Jonas,

Greetings from San Francisco!

I rebooted the PC and it seems to be working again. I have the Starting
Resource at 6000.

For future reference, what *.ndf file, and what is the name of the variable
that controls Starting Resource?

Thank you,

George

**Comment by Jonitr0** [comment]
Hi George,

I am still getting a crash on launch when using any mod I create. But I believe it's not related to the Settings Editor or WME specifically. There have been instances of patches breaking modding before. I'll ask about this on discord.

The file is **GDConstantes.ndf**. Starting points are **ArgentInitialSetting**, and you might also have to edit **VictoryTypeDestructionLevelsTable**.

**Comment by Jonitr0** [comment]
Ok so it looks like the problem might be that WARNO selects the wrong mod when choosing a mod in the mod center. If you encounter a crash on launch, check the **Config.ini** in C:\Users\\**YourUserName**\Saved Games\EugenSystems\WARNO\mod and make sure "ActivatedMods" is set to your mod name

**Comment by bofhlusr** [comment]
Thank you Jonas.  I'll keep using and monitoring WME.  Please don't
hesitate to ask if you need me to test or check something. -George
