### ISSUE TITLE
Is it possible to update the operations editor?

### ISSUE THREAD

**Issue by Contrail326** [Jonitr0/WarnoModEditor#5]

**Comment by Jonitr0** [comment]
I'll hopefully be able to publish an update in the next few days that includes "Hold until relieved" and the strings from "Sledgehammer". The operation itself is however heavily scripted and thus editing it in the operation editor might not be possible unfortunately.

**Comment by Jonitr0** [comment]
Operation editor fixed and updated in v0.3.1b
