### ISSUE TITLE
File reading issue

### ISSUE THREAD

**Issue by yamato2199** [Jonitr0/WarnoModEditor#8]
I believe there might be an issue with the mod tool in reading the 'SubClusterLoadDepiction.ndf' file or due to some other reason. When I create a unit based on an existing one in the game, for instance, I made a 'Su_27S2' as a new unit using 'Su_27S' as a reference. I have checked the file structure and confirmed that there are no issues. Sometimes, I am able to generate the mod, but if I modify some data and try to regenerate the mod, an error occurs stating 'Modele_Su_27S2_SOV not found.' At this point, if I try to regenerate the mod while running the WARNO game simultaneously, a pop-up appears saying 'Only one instance of game can be launched at a time.' After this error, if I close the WARNO game and try to regenerate the mod, the problem disappears. I am not sure whether this is an issue with WARNO or with the modding tool.

**Comment by Jonitr0** [comment]
I'm going to need some more info on this one.
What exactly are you doing in your mod?
Have you tried generating the mod manually (by running the script from the terminal) and achieved different results?
It sounds like an issue with WARNO because WME does not change the generation process, it only backs up the config.ini file. You could try deleting it ("Edit" > "Delete Mod Configuration") before generating the mod and see if that helps

**Comment by yamato2199** [comment]
I haven't tried running the .bat file directly yet. Another solution I've found is to make a minor modification to the 'SubClusterLoadDepiction.ndf' file each time I generate the mod, such as adding a space. This prevents the 'Modele_Su_27S2_SOV not found' error from occurring. However, if I don't make any changes to the 'SubClusterLoadDepiction.ndf' file, even if the previous mod generation ran successfully, the next mod generation still results in a similar 'Modele_Su_27S2_SOV not found' error. I suspect that this issue is most likely caused by the .bat file associated with WARNO.

**Comment by Jonitr0** [comment]
I had a similar issue a while ago where generating a mod would need a small arbitrary change to work. That is not a problem with WME as far as I can tell, but with Warno's mod generation process. I'd recommend to report it to Eugen on their Discord
